INSERT INTO `categorie` (`CAT_CodeCategorieBiere`, `CAT_LibelleCategorieBiere`) VALUES
('ABB', 'Abbaye'),
('AMB', 'Ambrée'),
('ARO', 'Aromatisée'),
('ART', 'Artisanale'),
('BLC', 'Blanche'),
('BLD', 'Blonde'),
('BRT', 'Brut'),
('BRU', 'Brune'),
('CER', 'Cervoise'),
('FAR', 'Faro'),
('GUE', 'Gueuze'),
('KRI', 'Kriek'),
('NOI', 'Noire'),
('OKT', 'Oktoberfestbier'),
('RGE', 'Rouge'),
('ROU', 'Rousse'),
('SAI', 'Saison'),
('SAL', 'Sans Alcool');